### ISSUE TITLE
Composed tree: Use list semantics

### ISSUE THREAD

**Issue by LJWatson** [SVG-access-W3CG/use-case-examples#20]
When you use role="tree" it automatically puts screen readers into applications mode (as though role="application"). This means keyboard interaction has to be scripted.

Unless there is a case for this structure being interactive, suggest using list semantics instead.

**Comment by chaals** [comment]
I'll make a composed-tree-aria-list that uses list, then close the issue.

**Comment by chaals** [comment]
and… done! http://svg-access-w3cg.github.io/use-case-examples/composed-tree-aria-list.svg
