### ISSUE TITLE
Composed tree: Rearrange DOM structure

### ISSUE THREAD

**Issue by LJWatson** [SVG-access-W3CG/use-case-examples#22]
It'll take some work, but suggest rearranging the source order so the DOM structure reflects the relationships between nodes. Uncertain how well aria-owns is supported ATM.

Note: if aria-owns is used it should point to the listitem (or treeitem) container, rather than individual list/treeitems.

**Comment by chaals** [comment]
the DOM structure reflects a breadth-first walk of the tree.

Walking depth-first can be done using the links, which match the arrows going from one node to another.

The idea was to give two rational ways of exploring, one of which makes sense to a visual keyboard user...

The alternative would be to make the tree structure so you have the root as an overarching group that includes everything, with two children - the first-level branches of the tree with everything inside them, all the way down to the turtles at the bottom. Would that make more sense to a screenreader user?

(If so I'll make a test version, and then we can look at how that goes for keyboard users...)

**Comment by LJWatson** [comment]
The problem is that there is little useful support for aria-owns. Without that, there is little in the DOM structure to indicate the overall parent/child structure of the content to screen reader users. Initial (back/packet) test results:
http://ljwatson.github.io/test-cases/aria-owns/case.html

It's worse for aria-flowto.
http://ljwatson.github.io/test-cases/aria-flowto/case.html

**Comment by chaals** [comment]
Ended up using aria list roles to make this happen.

(using the links doesn't work in Safari, which is pretty sad)
